// Curated Mandarin vocabulary sample (HSK-aligned, beginner → advanced)
// id, hanzi, pinyin, meaning (id), exampleZh, exampleId, hsk, category, topic
window.VOCAB = [
  // ── HSK 1 ──────────────────────────────────────────────
  { id:"h1-01", hanzi:"你好", pinyin:"nǐ hǎo", meaning:"halo", exampleZh:"你好，我叫小明。", exampleId:"Halo, nama saya Xiao Ming.", hsk:1, category:"sapaan", topic:"perkenalan" },
  { id:"h1-02", hanzi:"谢谢", pinyin:"xiè xie", meaning:"terima kasih", exampleZh:"谢谢你的帮助。", exampleId:"Terima kasih atas bantuanmu.", hsk:1, category:"sapaan", topic:"perkenalan" },
  { id:"h1-03", hanzi:"再见", pinyin:"zài jiàn", meaning:"sampai jumpa", exampleZh:"明天见，再见！", exampleId:"Sampai besok, selamat tinggal!", hsk:1, category:"sapaan", topic:"perkenalan" },
  { id:"h1-04", hanzi:"我", pinyin:"wǒ", meaning:"saya", exampleZh:"我是学生。", exampleId:"Saya seorang pelajar.", hsk:1, category:"kata ganti", topic:"perkenalan" },
  { id:"h1-05", hanzi:"你", pinyin:"nǐ", meaning:"kamu", exampleZh:"你叫什么名字？", exampleId:"Siapa namamu?", hsk:1, category:"kata ganti", topic:"perkenalan" },
  { id:"h1-06", hanzi:"是", pinyin:"shì", meaning:"adalah", exampleZh:"这是我的书。", exampleId:"Ini buku saya.", hsk:1, category:"kata kerja", topic:"dasar" },
  { id:"h1-07", hanzi:"不", pinyin:"bù", meaning:"tidak", exampleZh:"我不喝咖啡。", exampleId:"Saya tidak minum kopi.", hsk:1, category:"kata keterangan", topic:"dasar" },
  { id:"h1-08", hanzi:"好", pinyin:"hǎo", meaning:"baik / bagus", exampleZh:"今天天气很好。", exampleId:"Cuaca hari ini bagus sekali.", hsk:1, category:"kata sifat", topic:"dasar" },
  { id:"h1-09", hanzi:"人", pinyin:"rén", meaning:"orang", exampleZh:"那里有很多人。", exampleId:"Di sana ada banyak orang.", hsk:1, category:"kata benda", topic:"dasar" },
  { id:"h1-10", hanzi:"家", pinyin:"jiā", meaning:"rumah / keluarga", exampleZh:"我家在北京。", exampleId:"Rumah saya di Beijing.", hsk:1, category:"kata benda", topic:"keluarga" },
  { id:"h1-11", hanzi:"妈妈", pinyin:"mā ma", meaning:"ibu", exampleZh:"我妈妈是老师。", exampleId:"Ibu saya seorang guru.", hsk:1, category:"keluarga", topic:"keluarga" },
  { id:"h1-12", hanzi:"爸爸", pinyin:"bà ba", meaning:"ayah", exampleZh:"爸爸在工作。", exampleId:"Ayah sedang bekerja.", hsk:1, category:"keluarga", topic:"keluarga" },
  { id:"h1-13", hanzi:"水", pinyin:"shuǐ", meaning:"air", exampleZh:"我想喝水。", exampleId:"Saya ingin minum air.", hsk:1, category:"makanan", topic:"makanan-minuman" },
  { id:"h1-14", hanzi:"茶", pinyin:"chá", meaning:"teh", exampleZh:"请给我一杯茶。", exampleId:"Tolong beri saya secangkir teh.", hsk:1, category:"makanan", topic:"makanan-minuman" },
  { id:"h1-15", hanzi:"吃", pinyin:"chī", meaning:"makan", exampleZh:"我们一起吃饭吧。", exampleId:"Ayo kita makan bersama.", hsk:1, category:"kata kerja", topic:"makanan-minuman" },
  { id:"h1-16", hanzi:"喝", pinyin:"hē", meaning:"minum", exampleZh:"你要喝茶吗？", exampleId:"Apakah kamu mau minum teh?", hsk:1, category:"kata kerja", topic:"makanan-minuman" },
  { id:"h1-17", hanzi:"一", pinyin:"yī", meaning:"satu", exampleZh:"我有一个问题。", exampleId:"Saya punya satu pertanyaan.", hsk:1, category:"angka", topic:"angka" },
  { id:"h1-18", hanzi:"二", pinyin:"èr", meaning:"dua", exampleZh:"桌子上有二本书。", exampleId:"Ada dua buku di meja.", hsk:1, category:"angka", topic:"angka" },
  { id:"h1-19", hanzi:"三", pinyin:"sān", meaning:"tiga", exampleZh:"三点开会。", exampleId:"Rapat jam tiga.", hsk:1, category:"angka", topic:"angka" },
  { id:"h1-20", hanzi:"今天", pinyin:"jīn tiān", meaning:"hari ini", exampleZh:"今天我很忙。", exampleId:"Hari ini saya sangat sibuk.", hsk:1, category:"waktu", topic:"waktu" },
  { id:"h1-21", hanzi:"明天", pinyin:"míng tiān", meaning:"besok", exampleZh:"明天见。", exampleId:"Sampai besok.", hsk:1, category:"waktu", topic:"waktu" },
  { id:"h1-22", hanzi:"爱", pinyin:"ài", meaning:"cinta / sayang", exampleZh:"我爱我的家人。", exampleId:"Saya sayang keluarga saya.", hsk:1, category:"kata kerja", topic:"emosi" },
  { id:"h1-23", hanzi:"朋友", pinyin:"péng you", meaning:"teman", exampleZh:"他是我的好朋友。", exampleId:"Dia teman baik saya.", hsk:1, category:"kata benda", topic:"perkenalan" },
  { id:"h1-24", hanzi:"学生", pinyin:"xué shēng", meaning:"pelajar", exampleZh:"我是大学生。", exampleId:"Saya mahasiswa.", hsk:1, category:"kata benda", topic:"sekolah" },
  { id:"h1-25", hanzi:"老师", pinyin:"lǎo shī", meaning:"guru", exampleZh:"王老师教我们汉语。", exampleId:"Pak Wang mengajarkan bahasa Mandarin kepada kami.", hsk:1, category:"kata benda", topic:"sekolah" },

  // ── HSK 2 ──────────────────────────────────────────────
  { id:"h2-01", hanzi:"喜欢", pinyin:"xǐ huān", meaning:"suka", exampleZh:"我喜欢吃中国菜。", exampleId:"Saya suka makan masakan Cina.", hsk:2, category:"kata kerja", topic:"emosi" },
  { id:"h2-02", hanzi:"因为", pinyin:"yīn wèi", meaning:"karena", exampleZh:"因为下雨，我们没去。", exampleId:"Karena hujan, kami tidak pergi.", hsk:2, category:"kata sambung", topic:"sebab-akibat" },
  { id:"h2-03", hanzi:"所以", pinyin:"suǒ yǐ", meaning:"jadi / oleh karena itu", exampleZh:"我累了，所以想休息。", exampleId:"Saya capek, jadi ingin istirahat.", hsk:2, category:"kata sambung", topic:"sebab-akibat" },
  { id:"h2-04", hanzi:"但是", pinyin:"dàn shì", meaning:"tetapi", exampleZh:"我想去，但是很忙。", exampleId:"Saya ingin pergi, tetapi sangat sibuk.", hsk:2, category:"kata sambung", topic:"sebab-akibat" },
  { id:"h2-05", hanzi:"觉得", pinyin:"jué de", meaning:"berpikir / merasa", exampleZh:"我觉得这本书很好。", exampleId:"Saya rasa buku ini bagus.", hsk:2, category:"kata kerja", topic:"pendapat" },
  { id:"h2-06", hanzi:"知道", pinyin:"zhī dào", meaning:"tahu", exampleZh:"我知道这个问题。", exampleId:"Saya tahu jawaban pertanyaan ini.", hsk:2, category:"kata kerja", topic:"pendapat" },
  { id:"h2-07", hanzi:"希望", pinyin:"xī wàng", meaning:"berharap", exampleZh:"我希望明天是晴天。", exampleId:"Saya berharap besok cerah.", hsk:2, category:"kata kerja", topic:"emosi" },
  { id:"h2-08", hanzi:"帮助", pinyin:"bāng zhù", meaning:"membantu", exampleZh:"谢谢你帮助我。", exampleId:"Terima kasih sudah membantu saya.", hsk:2, category:"kata kerja", topic:"sosial" },
  { id:"h2-09", hanzi:"开始", pinyin:"kāi shǐ", meaning:"memulai", exampleZh:"电影八点开始。", exampleId:"Film mulai jam delapan.", hsk:2, category:"kata kerja", topic:"waktu" },
  { id:"h2-10", hanzi:"最后", pinyin:"zuì hòu", meaning:"terakhir", exampleZh:"最后我们赢了。", exampleId:"Akhirnya kami menang.", hsk:2, category:"kata keterangan", topic:"urutan" },
  { id:"h2-11", hanzi:"一起", pinyin:"yì qǐ", meaning:"bersama", exampleZh:"我们一起去吧。", exampleId:"Ayo kita pergi bersama.", hsk:2, category:"kata keterangan", topic:"sosial" },
  { id:"h2-12", hanzi:"手机", pinyin:"shǒu jī", meaning:"ponsel", exampleZh:"我的手机没电了。", exampleId:"Ponsel saya kehabisan baterai.", hsk:2, category:"benda", topic:"teknologi" },
  { id:"h2-13", hanzi:"电脑", pinyin:"diàn nǎo", meaning:"komputer", exampleZh:"这台电脑很快。", exampleId:"Komputer ini sangat cepat.", hsk:2, category:"benda", topic:"teknologi" },
  { id:"h2-14", hanzi:"工作", pinyin:"gōng zuò", meaning:"pekerjaan / bekerja", exampleZh:"我在一家公司工作。", exampleId:"Saya bekerja di sebuah perusahaan.", hsk:2, category:"kata kerja", topic:"pekerjaan" },
  { id:"h2-15", hanzi:"医院", pinyin:"yī yuàn", meaning:"rumah sakit", exampleZh:"他在医院工作。", exampleId:"Dia bekerja di rumah sakit.", hsk:2, category:"tempat", topic:"kesehatan" },
  { id:"h2-16", hanzi:"商店", pinyin:"shāng diàn", meaning:"toko", exampleZh:"商店九点开门。", exampleId:"Toko buka jam sembilan.", hsk:2, category:"tempat", topic:"belanja" },
  { id:"h2-17", hanzi:"买", pinyin:"mǎi", meaning:"membeli", exampleZh:"我想买一件衣服。", exampleId:"Saya ingin membeli sepotong pakaian.", hsk:2, category:"kata kerja", topic:"belanja" },
  { id:"h2-18", hanzi:"卖", pinyin:"mài", meaning:"menjual", exampleZh:"这家店卖水果。", exampleId:"Toko ini menjual buah.", hsk:2, category:"kata kerja", topic:"belanja" },
  { id:"h2-19", hanzi:"钱", pinyin:"qián", meaning:"uang", exampleZh:"这个多少钱？", exampleId:"Ini harganya berapa?", hsk:2, category:"kata benda", topic:"belanja" },
  { id:"h2-20", hanzi:"贵", pinyin:"guì", meaning:"mahal", exampleZh:"这件衣服太贵了。", exampleId:"Pakaian ini terlalu mahal.", hsk:2, category:"kata sifat", topic:"belanja" },

  // ── HSK 3 ──────────────────────────────────────────────
  { id:"h3-01", hanzi:"方便", pinyin:"fāng biàn", meaning:"nyaman / mudah", exampleZh:"这里交通很方便。", exampleId:"Transportasi di sini sangat nyaman.", hsk:3, category:"kata sifat", topic:"kehidupan" },
  { id:"h3-02", hanzi:"重要", pinyin:"zhòng yào", meaning:"penting", exampleZh:"健康很重要。", exampleId:"Kesehatan itu penting.", hsk:3, category:"kata sifat", topic:"pendapat" },
  { id:"h3-03", hanzi:"决定", pinyin:"jué dìng", meaning:"memutuskan", exampleZh:"我决定去留学。", exampleId:"Saya memutuskan untuk kuliah di luar negeri.", hsk:3, category:"kata kerja", topic:"pendapat" },
  { id:"h3-04", hanzi:"准备", pinyin:"zhǔn bèi", meaning:"bersiap / mempersiapkan", exampleZh:"我在准备考试。", exampleId:"Saya sedang mempersiapkan ujian.", hsk:3, category:"kata kerja", topic:"sekolah" },
  { id:"h3-05", hanzi:"完成", pinyin:"wán chéng", meaning:"menyelesaikan", exampleZh:"我完成了作业。", exampleId:"Saya sudah menyelesaikan PR.", hsk:3, category:"kata kerja", topic:"pekerjaan" },
  { id:"h3-06", hanzi:"经验", pinyin:"jīng yàn", meaning:"pengalaman", exampleZh:"他有丰富的工作经验。", exampleId:"Dia punya pengalaman kerja yang kaya.", hsk:3, category:"kata benda", topic:"pekerjaan" },
  { id:"h3-07", hanzi:"机会", pinyin:"jī huì", meaning:"kesempatan", exampleZh:"这是一个好机会。", exampleId:"Ini kesempatan yang bagus.", hsk:3, category:"kata benda", topic:"pekerjaan" },
  { id:"h3-08", hanzi:"环境", pinyin:"huán jìng", meaning:"lingkungan", exampleZh:"这里的环境很安静。", exampleId:"Lingkungan di sini sangat tenang.", hsk:3, category:"kata benda", topic:"alam" },
  { id:"h3-09", hanzi:"提高", pinyin:"tí gāo", meaning:"meningkatkan", exampleZh:"我想提高汉语水平。", exampleId:"Saya ingin meningkatkan level bahasa Mandarin.", hsk:3, category:"kata kerja", topic:"sekolah" },
  { id:"h3-10", hanzi:"影响", pinyin:"yǐng xiǎng", meaning:"mempengaruhi / pengaruh", exampleZh:"天气影响了计划。", exampleId:"Cuaca mempengaruhi rencana.", hsk:3, category:"kata kerja", topic:"sebab-akibat" },
  { id:"h3-11", hanzi:"认真", pinyin:"rèn zhēn", meaning:"sungguh-sungguh", exampleZh:"他学习很认真。", exampleId:"Dia belajar dengan sungguh-sungguh.", hsk:3, category:"kata sifat", topic:"sekolah" },
  { id:"h3-12", hanzi:"复杂", pinyin:"fù zá", meaning:"rumit", exampleZh:"这个问题有点复杂。", exampleId:"Masalah ini agak rumit.", hsk:3, category:"kata sifat", topic:"pendapat" },
  { id:"h3-13", hanzi:"简单", pinyin:"jiǎn dān", meaning:"sederhana", exampleZh:"这个方法很简单。", exampleId:"Metode ini sederhana.", hsk:3, category:"kata sifat", topic:"pendapat" },
  { id:"h3-14", hanzi:"旅游", pinyin:"lǚ yóu", meaning:"berwisata", exampleZh:"暑假我去中国旅游。", exampleId:"Liburan musim panas saya wisata ke Cina.", hsk:3, category:"kata kerja", topic:"perjalanan" },
  { id:"h3-15", hanzi:"机场", pinyin:"jī chǎng", meaning:"bandara", exampleZh:"机场离这里很远。", exampleId:"Bandara jauh dari sini.", hsk:3, category:"tempat", topic:"perjalanan" },

  // ── HSK 4 ──────────────────────────────────────────────
  { id:"h4-01", hanzi:"适应", pinyin:"shì yìng", meaning:"beradaptasi", exampleZh:"我很快适应了新环境。", exampleId:"Saya cepat beradaptasi dengan lingkungan baru.", hsk:4, category:"kata kerja", topic:"kehidupan" },
  { id:"h4-02", hanzi:"鼓励", pinyin:"gǔ lì", meaning:"mendorong / menyemangati", exampleZh:"老师鼓励我们多说汉语。", exampleId:"Guru mendorong kami berbicara lebih banyak Mandarin.", hsk:4, category:"kata kerja", topic:"sosial" },
  { id:"h4-03", hanzi:"安排", pinyin:"ān pái", meaning:"mengatur / jadwal", exampleZh:"我安排了会议时间。", exampleId:"Saya sudah mengatur waktu rapat.", hsk:4, category:"kata kerja", topic:"pekerjaan" },
  { id:"h4-04", hanzi:"负责", pinyin:"fù zé", meaning:"bertanggung jawab", exampleZh:"他负责这个项目。", exampleId:"Dia bertanggung jawab atas proyek ini.", hsk:4, category:"kata kerja", topic:"pekerjaan" },
  { id:"h4-05", hanzi:"交流", pinyin:"jiāo liú", meaning:"berkomunikasi", exampleZh:"我们用中文交流。", exampleId:"Kami berkomunikasi dengan bahasa Cina.", hsk:4, category:"kata kerja", topic:"sosial" },
  { id:"h4-06", hanzi:"观点", pinyin:"guān diǎn", meaning:"pendapat / sudut pandang", exampleZh:"我同意你的观点。", exampleId:"Saya setuju dengan pendapatmu.", hsk:4, category:"kata benda", topic:"pendapat" },
  { id:"h4-07", hanzi:"态度", pinyin:"tài dù", meaning:"sikap", exampleZh:"他的态度很认真。", exampleId:"Sikapnya sangat serius.", hsk:4, category:"kata benda", topic:"pendapat" },
  { id:"h4-08", hanzi:"效果", pinyin:"xiào guǒ", meaning:"efek / hasil", exampleZh:"这个方法效果很好。", exampleId:"Metode ini hasilnya bagus.", hsk:4, category:"kata benda", topic:"sebab-akibat" },
  { id:"h4-09", hanzi:"发展", pinyin:"fā zhǎn", meaning:"pengembangan / berkembang", exampleZh:"城市正在快速发展。", exampleId:"Kota sedang berkembang pesat.", hsk:4, category:"kata kerja", topic:"masyarakat" },
  { id:"h4-10", hanzi:"科技", pinyin:"kē jì", meaning:"teknologi sains", exampleZh:"科技改变了生活。", exampleId:"Teknologi mengubah kehidupan.", hsk:4, category:"kata benda", topic:"teknologi" },
  { id:"h4-11", hanzi:"资源", pinyin:"zī yuán", meaning:"sumber daya", exampleZh:"我们要保护资源。", exampleId:"Kita harus melindungi sumber daya.", hsk:4, category:"kata benda", topic:"alam" },
  { id:"h4-12", hanzi:"挑战", pinyin:"tiǎo zhàn", meaning:"tantangan", exampleZh:"这是一个很大的挑战。", exampleId:"Ini tantangan yang sangat besar.", hsk:4, category:"kata benda", topic:"pekerjaan" },
  { id:"h4-13", hanzi:"成功", pinyin:"chéng gōng", meaning:"berhasil / sukses", exampleZh:"他成功完成了任务。", exampleId:"Dia berhasil menyelesaikan tugas.", hsk:4, category:"kata kerja", topic:"pekerjaan" },
  { id:"h4-14", hanzi:"努力", pinyin:"nǔ lì", meaning:"berusaha keras", exampleZh:"只要努力就会成功。", exampleId:"Selama berusaha keras pasti berhasil.", hsk:4, category:"kata kerja", topic:"sekolah" },
  { id:"h4-15", hanzi:"无论", pinyin:"wú lùn", meaning:"tidak peduli / bagaimanapun", exampleZh:"无论多难，我都要试。", exampleId:"Bagaimanapun sulitnya, saya harus mencoba.", hsk:4, category:"kata sambung", topic:"sebab-akibat" },

  // ── HSK 5 ──────────────────────────────────────────────
  { id:"h5-01", hanzi:"趋势", pinyin:"qū shì", meaning:"tren / kecenderungan", exampleZh:"这是一个新的趋势。", exampleId:"Ini adalah tren baru.", hsk:5, category:"kata benda", topic:"masyarakat" },
  { id:"h5-02", hanzi:"效率", pinyin:"xiào lǜ", meaning:"efisiensi", exampleZh:"我们需要提高工作效率。", exampleId:"Kita perlu meningkatkan efisiensi kerja.", hsk:5, category:"kata benda", topic:"pekerjaan" },
  { id:"h5-03", hanzi:"策略", pinyin:"cè lüè", meaning:"strategi", exampleZh:"这个策略很有效。", exampleId:"Strategi ini sangat efektif.", hsk:5, category:"kata benda", topic:"pekerjaan" },
  { id:"h5-04", hanzi:"潜在", pinyin:"qián zài", meaning:"potensial", exampleZh:"有潜在的风险。", exampleId:"Ada risiko potensial.", hsk:5, category:"kata sifat", topic:"analisis" },
  { id:"h5-05", hanzi:"显著", pinyin:"xiǎn zhù", meaning:"nyata / mencolok", exampleZh:"取得了显著的进步。", exampleId:"Mencapai kemajuan yang nyata.", hsk:5, category:"kata sifat", topic:"analisis" },
  { id:"h5-06", hanzi:"协调", pinyin:"xié tiáo", meaning:"mengoordinasikan", exampleZh:"我们需要协调各方意见。", exampleId:"Kita perlu mengoordinasikan berbagai pendapat.", hsk:5, category:"kata kerja", topic:"pekerjaan" },
  { id:"h5-07", hanzi:"意识", pinyin:"yì shí", meaning:"kesadaran", exampleZh:"环保意识越来越强。", exampleId:"Kesadaran lingkungan semakin kuat.", hsk:5, category:"kata benda", topic:"masyarakat" },
  { id:"h5-08", hanzi:"本质", pinyin:"běn zhì", meaning:"esensi", exampleZh:"要看问题的本质。", exampleId:"Harus melihat esensi masalah.", hsk:5, category:"kata benda", topic:"analisis" },
  { id:"h5-09", hanzi:"综合", pinyin:"zōng hé", meaning:"komprehensif / menggabungkan", exampleZh:"请综合各方面的信息。", exampleId:"Tolong gabungkan informasi dari berbagai aspek.", hsk:5, category:"kata kerja", topic:"analisis" },
  { id:"h5-10", hanzi:"局限", pinyin:"jú xiàn", meaning:"keterbatasan", exampleZh:"这个方法有局限。", exampleId:"Metode ini punya keterbatasan.", hsk:5, category:"kata benda", topic:"analisis" },

  // ── HSK 6 ──────────────────────────────────────────────
  { id:"h6-01", hanzi:"宏观", pinyin:"hóng guān", meaning:"makro", exampleZh:"从宏观角度看问题。", exampleId:"Melihat masalah dari sudut pandang makro.", hsk:6, category:"kata sifat", topic:"analisis" },
  { id:"h6-02", hanzi:"微观", pinyin:"wēi guān", meaning:"mikro", exampleZh:"微观层面也有变化。", exampleId:"Di tingkat mikro juga ada perubahan.", hsk:6, category:"kata sifat", topic:"analisis" },
  { id:"h6-03", hanzi:"悖论", pinyin:"bèi lùn", meaning:"paradoks", exampleZh:"这是一个有趣的悖论。", exampleId:"Ini paradoks yang menarik.", hsk:6, category:"kata benda", topic:"analisis" },
  { id:"h6-04", hanzi:"辩证", pinyin:"biàn zhèng", meaning:"dialektis", exampleZh:"用辩证的方法思考。", exampleId:"Berpikir dengan metode dialektis.", hsk:6, category:"kata sifat", topic:"analisis" },
  { id:"h6-05", hanzi:"共识", pinyin:"gòng shí", meaning:"konsensus", exampleZh:"我们达成了共识。", exampleId:"Kami mencapai konsensus.", hsk:6, category:"kata benda", topic:"masyarakat" },
  { id:"h6-06", hanzi:"格局", pinyin:"gé jú", meaning:"pola / konfigurasi", exampleZh:"全球格局正在变化。", exampleId:"Pola global sedang berubah.", hsk:6, category:"kata benda", topic:"masyarakat" },
  { id:"h6-07", hanzi:"底蕴", pinyin:"dǐ yùn", meaning:"kekayaan budaya / fondasi", exampleZh:"这座城市有深厚的文化底蕴。", exampleId:"Kota ini punya fondasi budaya yang dalam.", hsk:6, category:"kata benda", topic:"budaya" },
  { id:"h6-08", hanzi:"诠释", pinyin:"quán shì", meaning:"menginterpretasikan", exampleZh:"这部作品诠释了人性。", exampleId:"Karya ini menginterpretasikan sifat manusia.", hsk:6, category:"kata kerja", topic:"budaya" },
  { id:"h6-09", hanzi:"潜移默化", pinyin:"qián yí mò huà", meaning:"mempengaruhi secara halus", exampleZh:"文化在潜移默化中影响我们。", exampleId:"Budaya mempengaruhi kita secara halus.", hsk:6, category:"idiom", topic:"budaya" },
  { id:"h6-10", hanzi:"相辅相成", pinyin:"xiāng fǔ xiāng chéng", meaning:"saling melengkapi", exampleZh:"理论与实践相辅相成。", exampleId:"Teori dan praktik saling melengkapi.", hsk:6, category:"idiom", topic:"analisis" },
];
